"""Private document storage for the C2 isolated environment.

* Documents live on local disk under ``GOAA_C2_PRIVATE_FILES_DIR`` (0700).
* Files are written with mode 0600 and a random opaque key; the original file
  name is never used as a path component.
* There is **no** external/cloud object storage involved and the store is *not*
  public: reads only happen through short-lived signed links served by this API.
* The virus scanner is a stub and OCR is rules-only, so everything the store
  reports about a document is explicitly labelled as stub/best-effort.
"""

from __future__ import annotations

import hashlib
import os
import re
import secrets
from dataclasses import dataclass
from pathlib import Path

_SAFE_EXT = re.compile(r"^[a-z0-9]{1,8}$")


@dataclass(frozen=True)
class StoredObject:
    storage_key: str
    sha256: str
    size_bytes: int


def _extension_for(mime_type: str) -> str:
    mapping = {
        "image/jpeg": "jpg",
        "image/png": "png",
        "image/webp": "webp",
        "application/pdf": "pdf",
    }
    ext = mapping.get(mime_type, "bin")
    return ext if _SAFE_EXT.match(ext) else "bin"


def storage_root(private_files_dir: str) -> Path:
    root = Path(private_files_dir)
    root.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(root, 0o700)
    except PermissionError:  # pragma: no cover - owned by another user at runtime
        pass
    return root


def save_bytes(private_files_dir: str, mime_type: str, payload: bytes) -> StoredObject:
    """Atomically persist ``payload`` and return its opaque storage key."""
    root = storage_root(private_files_dir)
    digest = hashlib.sha256(payload).hexdigest()
    key = f"{secrets.token_hex(16)}.{_extension_for(mime_type)}"
    target = root / key
    tmp = root / f".{key}.part"
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
    except Exception:
        tmp.unlink(missing_ok=True)
        raise
    os.replace(tmp, target)
    os.chmod(target, 0o600)
    return StoredObject(storage_key=key, sha256=digest, size_bytes=len(payload))


def read_bytes(private_files_dir: str, storage_key: str) -> bytes:
    # storage keys are generated by us; refuse anything that is not a bare name
    if os.sep in storage_key or "/" in storage_key or storage_key.startswith("."):
        raise ValueError("invalid storage key")
    return (storage_root(private_files_dir) / storage_key).read_bytes()


def delete_bytes(private_files_dir: str, storage_key: str) -> bool:
    if os.sep in storage_key or "/" in storage_key or storage_key.startswith("."):
        raise ValueError("invalid storage key")
    path = storage_root(private_files_dir) / storage_key
    try:
        path.unlink()
        return True
    except FileNotFoundError:
        return False


def sniff_mime(payload: bytes) -> str | None:
    """Best-effort content sniffing so a caller cannot lie about the media type."""
    if payload.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if payload.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if payload[:4] == b"RIFF" and payload[8:12] == b"WEBP":
        return "image/webp"
    if payload.startswith(b"%PDF-"):
        return "application/pdf"
    return None


def scan_mode() -> str:
    """No real antivirus engine is attached in this environment."""
    return "stub"


def ocr_mode() -> str:
    """No real OCR engine is attached; only deterministic field rules run."""
    return "rules-only"
