'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { RuntimeBadge, useOrderRuntime } from '../components/OrderRuntimeBridge'
import { runtimeActions } from '../lib/order-runtime'

type Stage='estimate'|'accepted'|'paid'|'processing'|'delivered'|'completed'
type RequestType='text'|'date'|'amount'|'choice'|'image'|'pdf'|'file'
type SupplementItem={id:string;label:string;type:RequestType;required:boolean;answer?:string;attachments?:Array<{name:string;size:number;type:string}>;complete?:boolean}
type DeliveryFile={id:string;name:string;size:number;type:string;category:string;version:number}
type DemoState={stage:Stage;amount:number;serviceTitle:string;scope:string;agentMessages:string[];customerMessages:string[];supplementItems:SupplementItem[];supplementStatus?:'draft'|'collecting'|'complete';deliveryNote?:string;deliveryFiles:DeliveryFile[];deliverySubmittedAt?:string;updatedAt?:string;settlement?:'ready'|'paid'}

const KEY='goaa_order_demo_v1'
const initial:DemoState={stage:'estimate',amount:600,serviceTitle:'Life Protection Planning Service',scope:'Professional analysis, plan explanation, and follow-up service per the confirmed scope.',agentMessages:[],customerMessages:[],supplementItems:[],supplementStatus:'draft',deliveryFiles:[]}
const steps:Array<[Stage,string]>=[['estimate','Estimate'],['accepted','Estimate Accepted'],['paid','Paid'],['processing','Service in Progress'],['delivered','Delivered'],['completed','Completed']]

export default function CustomerOrderPage(){
 const runtime=useOrderRuntime('customer')
 const [state,setState]=useState<DemoState>(initial); const [message,setMessage]=useState(''); const [busy,setBusy]=useState('')
 useEffect(()=>{if(runtime.data?.mode==='api'){const r=runtime.data.order;const pkg=runtime.data.deliveryPackage;const sup=runtime.data.supplement;const mappedStage=(r.stage==='waiting_customer'?'processing':r.stage) as Stage;setState(s=>({...s,stage:mappedStage,amount:r.amount,serviceTitle:r.serviceTitle,supplementStatus:sup?.status==='complete'?'complete':sup?'collecting':s.supplementStatus,supplementItems:sup?.items?.map(x=>({id:x.id,label:x.label,type:x.type as RequestType,required:x.required,answer:x.answer,complete:x.status==='answered'||x.status==='complete',attachments:x.files?.map(f=>({name:f.name,size:0,type:'file'}))}))||[],deliveryNote:pkg?.note,deliveryFiles:pkg?.files?.map(f=>({id:f.id,name:f.name,size:f.size||0,type:f.mimeType||'file',category:f.category,version:f.version}))||[],deliverySubmittedAt:pkg?.submittedAt,updatedAt:r.updatedAt,settlement:r.settlement==='paid'?'paid':r.settlement==='ready'?'ready':undefined}));return}hydrate();const onStorage=(e:StorageEvent)=>{if(e.key===KEY)hydrate()};window.addEventListener('storage',onStorage);return()=>window.removeEventListener('storage',onStorage)},[runtime.data])
 function hydrate(){try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);setState({...initial,...parsed,deliveryFiles:parsed.deliveryFiles||[]})}}catch{}}
 function persist(next:DemoState){const value={...next,updatedAt:new Date().toISOString()};setState(value);localStorage.setItem(KEY,JSON.stringify(value))}
 function patch(values:Partial<DemoState>){persist({...state,...values})}
 async function run(label:string,fn:()=>Promise<unknown>){try{setBusy(label);await fn();await runtime.refresh()}finally{setBusy('')}}
 async function acceptEstimate(){await run('accept',()=>runtimeActions.acceptEstimate(runtime.orderId,runtime.token))}
 async function confirmCompletion(){await run('confirm',()=>runtimeActions.confirmCompletion(runtime.orderId,runtime.token))}
 async function sendMessage(){const clean=message.trim();if(!clean)return;setMessage('');await run('message',()=>runtimeActions.sendMessage(runtime.orderId,'customer',clean,runtime.token))}
 function updateItem(id:string,values:Partial<SupplementItem>){const items=state.supplementItems.map(x=>x.id===id?{...x,...values}:x);const complete=items.length>0&&items.every(x=>x.complete);patch({supplementItems:items,supplementStatus:complete?'complete':state.supplementStatus})}
 async function uploadFor(item:SupplementItem,e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;if(runtime.data?.mode==='api'){for(const file of files)await runtimeActions.uploadSupplementFile(runtime.orderId,item.id,file,runtime.token);await runtime.refresh();return}const attachments=files.map(f=>({name:f.name,size:f.size,type:f.type||'file'}));updateItem(item.id,{attachments,answer:`${attachments.length} file(s) uploaded`,complete:true})}
 async function saveText(item:SupplementItem,value:string){const clean=value.trim();if(!clean)return;if(runtime.data?.mode==='api'){await runtimeActions.answerSupplement(runtime.orderId,item.id,clean,runtime.token);await runtime.refresh();return}updateItem(item.id,{answer:clean,complete:true})}
 const index=steps.findIndex(([id])=>id===state.stage),agentLatest=useMemo(()=>state.agentMessages.slice(-3).reverse(),[state.agentMessages]);const collected=state.supplementItems.filter(x=>x.complete).length;const allCollected=state.supplementItems.length>0&&collected===state.supplementItems.length;const current=state.supplementItems.find(x=>!x.complete);const deliveryReady=index>=4&&state.deliveryFiles.length>0
 return <main style={{minHeight:'100vh',background:'#0b0a0d',color:'#f7f3fb',fontFamily:'Arial,sans-serif',padding:'34px 18px'}}><div style={{maxWidth:920,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{color:'#a89fad',fontSize:13}}>GOAA.ai · My Service</div><h1 style={{fontSize:30,margin:'8px 0'}}>Service Order</h1></div><div style={{display:'flex',gap:10,alignItems:'center'}}><RuntimeBadge mode={runtime.data?.mode} loading={runtime.loading} error={runtime.error}/><a href="/order-demo" style={{color:'#d8d1dc',fontSize:13}}>Back to Three-Role Test Center</a></div></div><p style={{color:'#aaa2ae',marginTop:0}}>Order #{runtime.orderId}</p>
  <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap'}}><div><div style={eyebrow}>Professional Estimate</div><h2 style={{margin:'8px 0'}}>{state.serviceTitle}</h2><p style={{color:'#aaa2ae',maxWidth:620}}>{state.scope}</p></div><div style={{textAlign:'right'}}><div style={{fontSize:34,fontWeight:800}}>${state.amount}</div><div style={{color:'#aaa2ae',fontSize:13}}>Estimated Professional Service Fee</div></div></div>{state.stage==='estimate'&&<div style={actions}><button style={secondary}>Not Now</button><button disabled={busy==='accept'} style={{...primary,opacity:busy==='accept'?.55:1}} onClick={acceptEstimate}>{busy==='accept'?'Processing…':`Accept $${state.amount} Quote`}</button></div>}{state.stage==='accepted'&&<div style={actions}><button style={primary} onClick={()=>patch({stage:'paid'})}>Simulate Stripe Payment ${state.amount}</button></div>}{index>=2&&<div style={{marginTop:18,color:'#9ee6b2'}}>✓ Estimate confirmed · Payment completed</div>}</section>
  <section style={card}><div style={eyebrow}>Order Progress</div><div style={{display:'grid',gap:14,marginTop:16}}>{steps.map(([id,label],i)=><div key={id} style={{display:'flex',gap:12,alignItems:'center',color:i<=index?'#f7f3fb':'#6f6874'}}><span style={{width:26,height:26,borderRadius:20,border:'1px solid #5a5260',display:'grid',placeItems:'center'}}>{i<index?'✓':i===index?'●':'○'}</span><span>{label}</span></div>)}</div>{state.stage==='paid'&&<Info text="Payment completed. Waiting for the professional to start service."/>}{state.stage==='processing'&&<Info text="Your professional is working on your order. Progress updates will sync here."/>}{state.stage==='delivered'&&<div style={{marginTop:18}}><Info text="The professional submitted the final delivery package. Review it, then confirm completion." good/><button disabled={busy==='confirm'} style={{...primary,marginTop:12,opacity:busy==='confirm'?.55:1}} onClick={confirmCompletion}>{busy==='confirm'?'Confirming…':'Confirm Service Complete'}</button></div>}{state.stage==='completed'&&<div style={{marginTop:18,padding:14,borderRadius:12,background:'#132219',color:'#a9edbc'}}>✓ Service confirmed complete. Deliverables stay saved to this order.</div>}</section>
  {state.supplementItems.length>0&&<section style={{...card,borderColor:'#4a3c69'}}><div style={eyebrow}>Supplement Assistant</div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'8px 0'}}>Your professional needs some additional information</h2><p style={{color:'#aaa2ae',lineHeight:1.65,marginTop:0}}>Complete each item as prompted. The system checks for gaps and consolidates everything once collected.</p></div><span style={{color:allCollected?'#9ee6b2':'#cbb9ff',fontWeight:700}}>{collected}/{state.supplementItems.length} Completed</span></div>
    {allCollected?<div style={{padding:14,borderRadius:12,background:'#132219',color:'#a9edbc'}}><b>✓ All information collected</b><div style={{marginTop:7,fontSize:13}}>Your full information package is ready — no need to resend anything.</div></div>:state.supplementStatus==='collecting'?<div><div style={{padding:13,borderRadius:10,background:'#171321',color:'#d7cff0',marginBottom:14}}><b>Currently needed:</b> {current?.label}</div><div style={{display:'grid',gap:10}}>{state.supplementItems.map(item=><div key={item.id} style={{padding:14,border:'1px solid #302a39',borderRadius:12,background:item.complete?'#122018':'#111014'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontWeight:750}}>{item.label}</div><div style={{fontSize:12,color:'#8f8999',marginTop:4}}>{typeLabel(item.type)} · {item.required?'Required':'Optional'}</div></div><span style={{color:item.complete?'#86efac':'#8f8999'}}>{item.complete?'✓ Completed':'Pending'}</span></div>{!item.complete&&isFileType(item.type)&&<label style={{...primary,display:'inline-block',marginTop:12}}>Upload {typeLabel(item.type)}<input type="file" multiple={item.type==='file'} accept={item.type==='image'?'image/*':item.type==='pdf'?'application/pdf':undefined} onChange={e=>uploadFor(item,e)} style={{display:'none'}}/></label>}{!item.complete&&!isFileType(item.type)&&<input type={item.type==='date'?'date':item.type==='amount'?'number':'text'} placeholder="Enter…" style={{...input,marginTop:12}} onBlur={e=>saveText(item,e.target.value)}/>} {item.complete&&<div style={{marginTop:10,fontSize:13,color:'#c7c0cf'}}>{item.answer}{item.attachments?.length?<div style={{marginTop:6}}>{item.attachments.map((a,i)=><span key={i} style={{display:'inline-block',marginRight:8,padding:'4px 8px',borderRadius:8,background:'#1c1921'}}>📎 {a.name}</span>)}</div>:null}</div>}</div>)}</div></div>:<Info text="Your professional is preparing the list of requested items."/>}
  </section>}
  {deliveryReady&&<section style={{...card,borderColor:'#4b6c5a'}}><div style={eyebrow}>Deliverables</div><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'8px 0'}}>Final Deliverables</h2><p style={{color:'#aaa2ae',lineHeight:1.65,margin:0}}>{state.deliveryNote||'The professional completed this service. These files are kept as the final deliverables for this order.'}</p></div><span style={{color:'#9ee6b2',fontWeight:700}}>{state.deliveryFiles.length} files</span></div><div style={{display:'grid',gap:9,marginTop:16}}>{state.deliveryFiles.map(file=><div key={file.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:12,border:'1px solid #2c3c33',borderRadius:11,background:'#101713'}}><div><b>📄 {file.name}</b><div style={{fontSize:12,color:'#8f9992',marginTop:4}}>{file.category} · Version {file.version} · {formatSize(file.size)}</div></div><button onClick={()=>alert(`Download ${file.name}`)} style={secondary}>Download</button></div>)}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:14}}><button onClick={()=>alert('Download full delivery package ZIP')} style={primary}>Download Full Package</button>{state.deliverySubmittedAt&&<span style={{alignSelf:'center',fontSize:12,color:'#8f9992'}}>Submitted:{new Date(state.deliverySubmittedAt).toLocaleString('en-US')}</span>}</div></section>}
  <section style={card}><div style={eyebrow}>Service Chat</div><h2 style={{margin:'8px 0'}}>Chat with Your Professional</h2><div style={{display:'flex',gap:10,marginTop:16,flexWrap:'wrap'}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Type your message…" style={input}/><button disabled={busy==='message'} onClick={sendMessage} style={{...primary,opacity:busy==='message'?.55:1}}>{busy==='message'?'Sending…':'Send'}</button></div>{agentLatest.length>0&&<div style={{marginTop:16}}><div style={{color:'#8f8999',fontSize:12}}>Recent Messages from Professional</div>{agentLatest.map((m,i)=><div key={i} style={{marginTop:8,background:'#17151a',padding:'10px 12px',borderRadius:10}}>{m}</div>)}</div>}</section>
  {!deliveryReady&&<section style={card}><div style={eyebrow}>Delivery & Files</div><h2 style={{margin:'8px 0'}}>Waiting for Your Professional</h2><p style={{color:'#aaa2ae'}}>Final delivery files are saved to this order — you can view and download them anytime after completion.</p></section>}
 </div></main>
}
function isFileType(v:RequestType){return v==='image'||v==='pdf'||v==='file'}
function formatSize(v:number){if(v<1024)return `${v} B`;if(v<1024*1024)return `${Math.round(v/1024)} KB`;return `${(v/1024/1024).toFixed(1)} MB`}
function typeLabel(v:RequestType){return ({text:'Text',date:'Date',amount:'Amount',choice:'Choice',image:'Image',pdf:'PDF',file:'File'} as Record<RequestType,string>)[v]}
function Info({text,good=false}:{text:string;good?:boolean}){return <div style={{marginTop:18,padding:13,borderRadius:10,background:good?'#132219':'#17151a',color:good?'#a9edbc':'#d7d1dc'}}>{text}</div>}
const card={background:'#111014',border:'1px solid #2b2730',borderRadius:18,padding:22,marginTop:18} as const
const eyebrow={color:'#a89fad',fontSize:12,letterSpacing:'.08em',textTransform:'uppercase' as const}
const actions={display:'flex',justifyContent:'flex-end',gap:10,marginTop:18,flexWrap:'wrap' as const}
const primary={background:'#f4eef8',color:'#171319',border:0,borderRadius:10,padding:'11px 16px',fontWeight:750,cursor:'pointer'} as const
const secondary={background:'transparent',color:'#d8d1dc',border:'1px solid #4a444f',borderRadius:10,padding:'11px 16px',fontWeight:650,cursor:'pointer'} as const
const input={flex:1,minWidth:220,background:'#0c0b0e',border:'1px solid #3b3540',borderRadius:10,padding:'12px 14px',color:'#fff',outline:'none'} as const
