import type { OrderSummary, SupplementRequest } from './order-api'

export type EscalationLevel='normal'|'attention'|'recommended'
export type EscalationTarget='none'|'customer'|'professional'|'goaa_support'
export type AgentEscalation={level:EscalationLevel;target:EscalationTarget;title:string;reason:string;customerCopy:string;professionalCopy:string;safeAction:string;automaticActionAllowed:false}

type Input={order:OrderSummary;supplement:SupplementRequest|null;inactiveHours:number}

export function deriveAgentEscalation({order,supplement,inactiveHours:h}:Input):AgentEscalation{
 const pending=(supplement?.items||[]).some(x=>x.required&&!['answered','complete','skipped'].includes(x.status))
 if(order.stage==='completed')return base('normal','none','Matter completed','The canonical order is complete.','This Matter is complete.','The order is complete.','Keep the record available; do not manufacture follow-up.')
 if(order.stage==='estimate'&&!order.estimate&&h>=96)return base('recommended','professional','Professional follow-up recommended','A matched Matter has had no estimate for an extended period.','I recommend a GOAA follow-up with the professional. You do not need to chase them yourself.','This Matter has been waiting for an estimate. Review it before GOAA support intervention becomes appropriate.','Recommend follow-up only; do not send, reassign, penalize, or cancel automatically.')
 if(order.stage==='estimate'&&order.estimate&&h>=168)return base('recommended','customer','Customer decision follow-up recommended','The estimate has been awaiting a customer decision for an extended period.','You still control the decision. I can keep the Matter open while you review the scope and fee.','The customer has not accepted the estimate. Do not infer consent from silence.','Recommend a respectful reminder only; no pressure, auto-acceptance, or cancellation.')
 if(order.stage==='accepted'&&h>=120)return base('recommended','customer','Payment decision follow-up recommended','Accepted scope remains unpaid for an extended period.','The service will not start until you choose to complete payment.','Do not begin paid execution until payment is verified.','Recommend reminder only; never charge automatically.')
 if(pending&&h>=168)return base('recommended','customer','Information follow-up recommended','Required customer information remains outstanding.','The Matter is waiting on information from you. I can keep tracking once it is provided.','Required information remains outstanding; avoid repeated or expanding requests.','Recommend one clear consolidated reminder; do not fabricate missing information.')
 if(order.stage==='paid'&&h>=72)return base('recommended','professional','Execution follow-up recommended','Verified payment exists but professional execution has not started.','Payment is confirmed. I recommend GOAA follow up on the start of execution.','The paid order has not entered active processing. Review the accepted scope and begin or explain the blocker.','Recommend follow-up; do not mark processing without real professional action.')
 if(order.stage==='processing'&&h>=240)return base('recommended','professional','Progress update recommended','Active execution has had no canonical workflow activity for an extended period.','The service is still open. I recommend requesting a verified progress update.','The order has had no recent workflow activity. Provide a real update, request needed information, or deliver when appropriate.','Recommend progress check only; do not invent progress or completion.')
 if(order.stage==='delivered'&&h>=168)return base('recommended','customer','Completion review follow-up recommended','Delivery remains unconfirmed for an extended period.','Please review the deliverables when ready. I will not close the Matter without real confirmation.','Delivery is awaiting the customer. Do not confirm completion on their behalf.','Recommend review reminder only; never auto-confirm completion.')
 return base('normal','none','No escalation recommended','The current delay does not meet the bounded escalation threshold.','I’m still tracking this Matter.','Continue the current workflow.','No external action should be generated from this policy.')
}
function base(level:EscalationLevel,target:EscalationTarget,title:string,reason:string,customerCopy:string,professionalCopy:string,safeAction:string):AgentEscalation{return{level,target,title,reason,customerCopy,professionalCopy,safeAction,automaticActionAllowed:false}}
