'use client'

import { useEffect, useState } from 'react'
import { orderApi, type InvoiceRecord, type OrderSummary } from '../lib/order-api'

const K={order:'goaa_active_order_id',customer:'goaa_order_customer_token',agent:'goaa_order_agent_token',admin:'goaa_order_admin_token'}
export default function FullFlowLive(){
 const [orderId,setOrderId]=useState('')
 const [customerToken,setCustomerToken]=useState('')
 const [agentToken,setAgentToken]=useState('')
 const [adminToken,setAdminToken]=useState('')
 const [customer,setCustomer]=useState<OrderSummary|null>(null)
 const [agent,setAgent]=useState<OrderSummary|null>(null)
 const [admin,setAdmin]=useState<OrderSummary|null>(null)
 const [need,setNeed]=useState('I want to plan life protection for my family and would like help reviewing suitable options.')
 const [title,setTitle]=useState('Family Protection Planning Consultation')
 const [scope,setScope]=useState('Needs analysis\nPlan comparison\nApplication support\nOngoing service')
 const [amount,setAmount]=useState(600)
 const [invoice,setInvoice]=useState<InvoiceRecord|null>(null)
 const [busy,setBusy]=useState('')
 const [error,setError]=useState('')
 useEffect(()=>{setOrderId(localStorage.getItem(K.order)||'');setCustomerToken(localStorage.getItem(K.customer)||'');setAgentToken(localStorage.getItem(K.agent)||'');setAdminToken(localStorage.getItem(K.admin)||'')},[])
 async function refresh(id=orderId){if(!id)return;setError('');const jobs:Promise<void>[]=[];if(customerToken)jobs.push(orderApi.getOrder(id,customerToken).then(setCustomer).catch(e=>setError(v=>v||`Customer: ${e.message}`)));if(agentToken)jobs.push(orderApi.getOrder(id,agentToken).then(setAgent).catch(e=>setError(v=>v||`Agent: ${e.message}`)));if(adminToken)jobs.push(orderApi.adminGetOrder(id,adminToken).then(setAdmin).catch(e=>setError(v=>v||`Admin: ${e.message}`)));if(customerToken)jobs.push(orderApi.getInvoice(id,customerToken).then(setInvoice).catch(()=>{}));await Promise.all(jobs)}
 useEffect(()=>{if(!orderId)return;refresh();const t=setInterval(()=>refresh(),2500);return()=>clearInterval(t)},[orderId,customerToken,agentToken,adminToken])
 function saveSetup(){localStorage.setItem(K.order,orderId);localStorage.setItem(K.customer,customerToken);localStorage.setItem(K.agent,agentToken);localStorage.setItem(K.admin,adminToken);refresh()}
 async function run(name:string,fn:()=>Promise<unknown>){try{setBusy(name);setError('');await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
 async function createOrder(){await run('create',async()=>{const o=await orderApi.createOrder({need,category:'insurance',serviceTitle:'Professional Service Request'},customerToken);setOrderId(o.id);localStorage.setItem(K.order,o.id)})}
 async function checkoutConnect(){await run('connect',async()=>{const r=await orderApi.createConnectCheckout(orderId,customerToken);window.location.href=r.checkoutUrl})}
 async function match(){await run('match',()=>orderApi.requestMatch(orderId,customerToken))}
 async function sendEstimate(){await run('estimate',()=>orderApi.createEstimate(orderId,{serviceTitle:title,amount,scope,lines:[{label:title,amount}]},agentToken))}
 async function accept(){await run('accept',()=>orderApi.acceptEstimate(orderId,customerToken))}
 async function serviceCheckout(){await run('servicepay',async()=>{const r=await orderApi.createServiceCheckout(orderId,customerToken);window.location.href=r.checkoutUrl})}
 async function start(){await run('start',()=>orderApi.startService(orderId,agentToken))}
 async function confirm(){await run('confirm',()=>orderApi.confirmCompletion(orderId,customerToken))}
 async function makeInvoice(){await run('invoice',async()=>setInvoice(await orderApi.generateInvoice(orderId,agentToken)))}
 const display=customer||agent||admin
 return <main style={shell}><div style={wrap}>
  <header><div style={eyebrow}>GOAA · FULL FLOW LIVE V3 · REAL API</div><h1 style={h1}>Customer × Agent × Admin Live Console</h1><p style={muted}>This page no longer simulates order/payment state. All business state comes from the DO Order Engine; payment state is written back by Stripe Test Mode webhooks.</p></header>
  <section style={setup}><h2 style={h2}>Identity & Order Setup</h2><div style={setupGrid}><input value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="Service Order ID (leave blank for a new order)" style={input}/><input value={customerToken} onChange={e=>setCustomerToken(e.target.value)} placeholder="Customer Token" style={input}/><input value={agentToken} onChange={e=>setAgentToken(e.target.value)} placeholder="Agent Token" style={input}/><input value={adminToken} onChange={e=>setAdminToken(e.target.value)} placeholder="Admin Token" style={input}/></div><button onClick={saveSetup} style={secondary}>Save Setup / Refresh</button>{error&&<div style={errorBox}>API：{error}</div>}</section>
  <section style={status}><div><b>Order:</b>{orderId||'Not Created'}</div><div><b>Stage：</b>{display?.stage||'—'}</div><div><b>Amount：</b>${display?.amount||0}</div><div><b>Settlement：</b>{display?.settlement||'—'}</div></section>
  <div style={grid}>
   <Role title="Customer Client" tag="CUSTOMER"><label style={label}>Need</label><textarea value={need} onChange={e=>setNeed(e.target.value)} style={area}/>{!orderId&&<button onClick={createOrder} disabled={!customerToken||busy==='create'} style={primary}>1. Create Real Order</button>}{orderId&&<><button onClick={checkoutConnect} disabled={!customerToken||busy==='connect'} style={primary}>2. Stripe Test · Pay $39.9 Connection Fee</button><button onClick={match} disabled={!customerToken||busy==='match'} style={secondary}>3. Request Agent Match</button><button onClick={accept} disabled={!customerToken||busy==='accept'} style={secondary}>5. Accept Agent Estimate</button><button onClick={serviceCheckout} disabled={!customerToken||busy==='servicepay'} style={primary}>6. Stripe Test · Pay Service Fee</button><button onClick={confirm} disabled={!customerToken||busy==='confirm'} style={secondary}>9. Confirm Completion</button></>}{customer&&<Snapshot o={customer}/>} {invoice&&<div style={invoiceCard}><b>Invoice {invoice.invoiceNumber}</b><strong>${invoice.amount}</strong><span>{invoice.status}</span>{invoice.downloadUrl&&<a href={invoice.downloadUrl} target="_blank" rel="noreferrer">Download PDF</a>}</div>}</Role>
   <Role title="Agent Professional" tag="AGENT"><label style={label}>Service Name</label><input value={title} onChange={e=>setTitle(e.target.value)} style={input}/><label style={label}>Scope / Service Description</label><textarea value={scope} onChange={e=>setScope(e.target.value)} style={area}/><label style={label}>Your Quote USD</label><input type="number" min="1" value={amount} onChange={e=>setAmount(Number(e.target.value)||0)} style={input}/><div style={chips}>{[300,500,600,1000].map(v=><button key={v} onClick={()=>setAmount(v)} style={chip}>${v}</button>)}</div><button onClick={sendEstimate} disabled={!orderId||!agentToken||busy==='estimate'} style={primary}>4. Send Real Estimate</button><button onClick={start} disabled={!orderId||!agentToken||busy==='start'} style={secondary}>7. Start Service</button><a style={linkButton} href={`/agent-order-live?order=${encodeURIComponent(orderId)}`} target="_blank">8. Open Supplements / Delivery Workspace</a><button onClick={makeInvoice} disabled={!orderId||!agentToken||busy==='invoice'} style={secondary}>10. Generate Real Invoice</button>{agent&&<Snapshot o={agent}/>}</Role>
   <Role title="Admin Platform" tag="ADMIN"><p style={muted}>Admin observes and resolves exceptions only — never hand-crafts Paid / Settled. Settlement must progress via Customer Confirm → Order Engine → Stripe Connect/webhook.</p>{admin&&<Snapshot o={admin}/>}<a style={linkButton} href={`/admin-order-live?order=${encodeURIComponent(orderId)}`} target="_blank">Open Admin Live Order</a><a style={linkButton} href={`/customer-order-live?order=${encodeURIComponent(orderId)}`} target="_blank">Open Customer Live Order</a></Role>
  </div>
  <section style={footer}><b>V3 Acceptance:</b> create order → $39.9 Test Checkout → webhook Paid → Match → Agent quote → Customer Accept → service fee Test Checkout → webhook Paid/Held → Agent Start → Delivery Package → Customer Confirm → Settlement Ready → Stripe Connect Test → Paid → Invoice PDF。</section>
 </div></main>
}
function Role({title,tag,children}:{title:string;tag:string;children:React.ReactNode}){return <section style={card}><div style={eyebrow}>{tag}</div><h2 style={h2}>{title}</h2>{children}</section>}
function Snapshot({o}:{o:OrderSummary}){return <div style={snapshot}><div><span>Stage</span><b>{o.stage}</b></div><div><span>Service</span><b>{o.serviceTitle||'—'}</b></div><div><span>Amount</span><b>${o.amount||0}</b></div><div><span>Settlement</span><b>{o.settlement||'locked'}</b></div></div>}
const shell={minHeight:'100vh',background:'#0d0b12',color:'#f7f5fb',fontFamily:'Inter,Arial,sans-serif',padding:'32px 18px 70px'} as const,wrap={maxWidth:1400,margin:'0 auto'} as const,eyebrow={color:'#9d7cff',fontSize:12,fontWeight:850,letterSpacing:'.08em'} as const,h1={fontSize:34,margin:'8px 0'} as const,h2={fontSize:20,margin:'8px 0 16px'} as const,muted={color:'#9993a4',fontSize:13,lineHeight:1.65} as const,setup={marginTop:18,background:'#17151e',border:'1px solid #2b2734',borderRadius:18,padding:18} as const,setupGrid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9} as const,status={display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10,marginTop:14,background:'#17151e',border:'1px solid #2b2734',borderRadius:16,padding:16,fontSize:13} as const,grid={display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:16,marginTop:16} as const,card={background:'#17151e',border:'1px solid #2b2734',borderRadius:18,padding:20,minHeight:570} as const,label={display:'block',color:'#b4adbc',fontSize:12,fontWeight:700,margin:'11px 0 6px'} as const,input={width:'100%',boxSizing:'border-box' as const,border:'1px solid #393342',borderRadius:10,background:'#100e15',color:'#fff',padding:'11px 12px',outline:'none'} as const,area={...input,minHeight:92,resize:'vertical' as const,lineHeight:1.5} as const,primary={marginTop:10,width:'100%',border:0,borderRadius:10,background:'#7655df',color:'#fff',padding:'11px 14px',fontWeight:800,cursor:'pointer'} as const,secondary={...primary,background:'#25202f',border:'1px solid #453965'} as const,errorBox={marginTop:10,padding:10,borderRadius:10,background:'#3a1720',color:'#fecdd3',fontSize:12} as const,chips={display:'flex',gap:7,marginTop:8,flexWrap:'wrap' as const} as const,chip={border:'1px solid #393342',background:'#121018',color:'#ddd6e7',borderRadius:99,padding:'6px 10px',cursor:'pointer'} as const,linkButton={...secondary,display:'block',textAlign:'center' as const,textDecoration:'none',boxSizing:'border-box' as const} as const,snapshot={marginTop:16,borderTop:'1px solid #2f2a36',paddingTop:10,display:'grid',gap:7} as const,invoiceCard={marginTop:14,padding:14,borderRadius:12,background:'#f4f1f7',color:'#17131d',display:'grid',gap:5} as const,footer={marginTop:16,background:'#17151e',border:'1px solid #2b2734',borderRadius:16,padding:18,color:'#bbb3c4',fontSize:13,lineHeight:1.7} as const
