"""
GOAA Shell Capability V0 — Schema (刀 1)
=========================================
Pure data structures for ShellTask requests and validation results.
No execution logic, no subprocess imports.

Design spec: docs/architecture/GOAA_SHELL_CAPABILITY_V0_DESIGN.md
Policy version: shell-v0.1-knife1
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import Dict, List, Optional


class ValidationStatus(enum.Enum):
    """Result status of a shell-task validation."""

    VALID = "valid"
    REJECTED_POLICY = "rejected_policy"
    REJECTED_TEMPLATE = "rejected_template"
    REJECTED_RESOURCE = "rejected_resource"
    REJECTED_ARGUMENT = "rejected_argument"


class GitRevParseMode(enum.Enum):
    """Controlled enum for git rev-parse sub-operations."""

    HEAD_SHORT = "HEAD_SHORT"
    BRANCH_NAME = "BRANCH_NAME"


class ApprovedUnit(enum.Enum):
    """Approved systemd unit names for systemctl is-active."""

    GOAA_LOCAL_CONSOLE = "goaa-local-console"
    GOAA_WORKER_AGENT = "goaa-worker-agent"
    GOAA_TELEMETRY_WRITER = "goaa-telemetry-writer"
    OLLAMA = "ollama"
    GOAA_ROUTER = "goaa-router"


@dataclass(frozen=True)
class ShellTaskRequest:
    """
    Pure request payload for a shell-task validation.

    - Does NOT carry a raw shell command string.
    - Does NOT carry user-supplied argv.
    - Does NOT carry environment variables, cwd, or absolute paths.
    - Template-specific options use explicit typed fields (git_mode,
      unit_name), NOT generic metadata.
    - metadata is reserved for audit labels only and MUST NOT
      participate in argv generation.
    """

    task_id: str
    template_id: str
    resource_name: Optional[str] = None
    git_mode: Optional[GitRevParseMode] = None
    unit_name: Optional[ApprovedUnit] = None
    requested_by: Optional[str] = None
    approval_id: Optional[str] = None
    metadata: Dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class ShellValidationResult:
    """
    Immutable result produced by the Validator.

    ``resolved_argv`` is always generated by Policy from the fixed template;
    it is never taken from user input.
    """

    status: ValidationStatus
    template_id: str
    resource_name: Optional[str] = None
    resolved_argv: List[str] = field(default_factory=list)
    timeout_seconds: int = 10
    stdout_limit_bytes: int = 32768
    stderr_limit_bytes: int = 16384
    risk_level: str = "low"
    requires_approval: bool = False
    reason_code: str = ""
    reason: str = ""
    policy_version: str = "shell-v0.1-knife1"
