'use client'

import {useEffect,useState} from 'react'
import {listActionProposals,prepareActionRetry,proposalStatusLabel,type AgentActionProposal,type AgentAuthorizer} from '../lib/agent-action-proposals'
import {useOrderRuntime} from './OrderRuntimeBridge'

function actionLabel(value:string){return value.split('_').join(' ')}
export default function AgentActionHistory({role}:{role:'customer'|'agent'}){
 const runtime=useOrderRuntime(role,10000);const orderId=runtime.data?.order?.id;const [items,setItems]=useState<AgentActionProposal[]>([])
 useEffect(()=>{if(!orderId)return;const authorizer:AgentAuthorizer=role==='customer'?'customer':'professional';const load=()=>setItems(listActionProposals(orderId,authorizer).slice(0,8));load();window.addEventListener('goaa-agent-action-proposals-updated',load);const t=window.setInterval(load,5000);return()=>{window.removeEventListener('goaa-agent-action-proposals-updated',load);window.clearInterval(t)}},[orderId,role])
 if(!orderId||!items.length)return null
 function prepareRetry(id:string){prepareActionRetry(id)}
 return <section style={{maxWidth:1180,margin:'10px auto 0',padding:'0 18px',fontFamily:'Inter,Arial,sans-serif'}}><div style={{border:'1px solid rgba(148,163,184,.18)',borderRadius:16,padding:14,background:'#0b1220',color:'#e5e7eb'}}><div style={{fontSize:10,fontWeight:850,letterSpacing:'.08em',color:'#94a3b8'}}>{role==='customer'?'AI BUTLER':'PROFESSIONAL AI ASSISTANT'} · ACTION HISTORY</div><div style={{fontSize:12,fontWeight:800,marginTop:5}}>Authorized action record on this device</div><div style={{fontSize:9,lineHeight:1.45,color:'#64748b',marginTop:4}}>This is a local transparency log, not yet the server audit source of truth. External actions are only shown as executed when the canonical Order Engine call returned successfully. Failed actions never retry silently.</div><div style={{display:'grid',gap:7,marginTop:9}}>{items.map(item=><div key={item.id} style={{border:'1px solid rgba(148,163,184,.12)',borderRadius:10,padding:9,background:'#0f172a'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,fontSize:10,fontWeight:750}}><span>{item.title}</span><span>{proposalStatusLabel(item.status)}</span></div><div style={{fontSize:9,color:'#94a3b8',marginTop:4}}>{actionLabel(item.actionType)} · {new Date(item.createdAt).toLocaleString()}</div>{item.retryOf&&<div style={{fontSize:9,color:'#64748b',marginTop:3}}>Prepared as an explicit retry of a failed proposal.</div>}{item.status==='superseded'&&<div style={{fontSize:9,color:'#93c5fd',marginTop:4}}>Superseded because a newer proposal scope replaced this one before execution.</div>}{item.canonicalResultKind&&<div style={{fontSize:9,color:'#86efac',marginTop:4}}>Canonical receipt: {item.canonicalResultKind}{item.canonicalResultId?` · ${item.canonicalResultId}`:''}</div>}{item.failureMessage&&<div style={{fontSize:9,color:'#fca5a5',marginTop:4}}>Failure: {item.failureMessage}</div>}{item.status==='failed'&&<button type="button" onClick={()=>prepareRetry(item.id)} style={{marginTop:7,border:'1px solid rgba(148,163,184,.2)',borderRadius:999,background:'transparent',color:'#cbd5e1',padding:'5px 8px',fontSize:9,fontWeight:750}}>Prepare retry — do not execute</button>}</div>)}</div></div></section>
}
