'use client'

import { useEffect, useState } from 'react'
import { PersonalAgentMatter, readMatterHistory, restoreMatter, syncLegacyWorkspaceToCurrentMatter } from '../lib/personal-agent-matter'
import MatterAssessmentPanel from './MatterAssessmentPanel'
import MatterActionPlan from './MatterActionPlan'
import MatterProfessionalConnect from './MatterProfessionalConnect'

const STATUS_LABEL = { active: 'Active', professional_handoff: 'Professional Handoff', completed: 'Completed' } as const
function shortDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }
export default function AgentMattersOverview() {
 const [matter,setMatter]=useState<PersonalAgentMatter|null>(null); const [history,setHistory]=useState<PersonalAgentMatter[]>([]); const [switchingId,setSwitchingId]=useState<string|null>(null)
 useEffect(()=>{const sync=()=>{setMatter(syncLegacyWorkspaceToCurrentMatter());setHistory(readMatterHistory())};sync();const timer=window.setInterval(sync,1200);window.addEventListener('storage',sync);return()=>{window.clearInterval(timer);window.removeEventListener('storage',sync)}},[])
 function switchMatter(item:PersonalAgentMatter){if(switchingId||item.id===matter?.id)return;setSwitchingId(item.id);const restored=restoreMatter(item.id);if(!restored){setSwitchingId(null);return}window.location.reload()}
 const factCount=matter?Object.keys(matter.knownFacts).length:0; const blueprintCount=matter?.blueprint.length||0; const previousMatters=history.filter((item)=>item.id!==matter?.id).slice(0,4)
 return <section id="agent-matters" aria-label="My AI Agent matters" style={{maxWidth:1160,margin:'12px auto 0',padding:'14px 18px',border:'1px solid rgba(255,255,255,0.08)',borderRadius:18,background:'rgba(255,255,255,0.018)'}}>
  <div style={{display:'flex',alignItems:'end',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><div style={{color:'#a78bfa',fontSize:11,letterSpacing:'0.14em',textTransform:'uppercase'}}>My Agent Matters</div><div style={{color:'#f5f3ff',fontSize:18,fontWeight:700,marginTop:3}}>One long-term AI Agent. Many things handled for you.</div></div><div style={{color:'#8f8a9e',fontSize:12}}>{history.length?`${history.length} matter${history.length===1?'':'s'} remembered`:'Each matter gets its own Action Blueprint.'}</div></div>
  <div style={{marginTop:12,display:'grid',gridTemplateColumns:'minmax(0, 1.3fr) minmax(240px, .7fr)',gap:10}}>
   <article style={{border:'1px solid rgba(139, 92, 246, 0.30)',borderRadius:14,padding:'13px 14px',background:'rgba(124, 58, 237, 0.10)'}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><div><div style={{color:'#a78bfa',fontSize:10,textTransform:'uppercase',letterSpacing:'0.12em'}}>Current Matter</div><strong style={{display:'block',marginTop:4,color:'#ede9fe',fontSize:14}}>{matter?.title||'Start a conversation to create your first matter'}</strong></div><span style={{color:matter?.status==='completed'?'#c4b5fd':'#34d399',fontSize:11,whiteSpace:'nowrap'}}>● {matter?STATUS_LABEL[matter.status]:'Ready'}</span></div>
    {matter?<><p style={{color:'#a6a1b2',fontSize:12,lineHeight:1.55,margin:'8px 0 0'}}>Conversation, recognized facts, and the Action Blueprint stay attached to this matter as your Agent moves it forward.</p><div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:9}}><span style={{border:'1px solid rgba(255,255,255,0.08)',borderRadius:999,padding:'5px 8px',color:'#aaa5b7',fontSize:10}}>{matter.thread.length} messages</span><span style={{border:'1px solid rgba(255,255,255,0.08)',borderRadius:999,padding:'5px 8px',color:'#aaa5b7',fontSize:10}}>{factCount} known facts</span><span style={{border:'1px solid rgba(255,255,255,0.08)',borderRadius:999,padding:'5px 8px',color:'#aaa5b7',fontSize:10}}>{blueprintCount||5} blueprint steps</span>{matter.source==='agent_signal'&&<span style={{border:'1px solid rgba(52,211,153,0.16)',borderRadius:999,padding:'5px 8px',color:'#a7f3d0',fontSize:10}}>From Agent Inbox</span>}</div><MatterAssessmentPanel matter={matter}/><MatterActionPlan matter={matter}/><MatterProfessionalConnect matter={matter}/></>:<p style={{color:'#a6a1b2',fontSize:12,lineHeight:1.55,margin:'8px 0 0'}}>Your first request will become a Matter. Your Agent will keep its conversation, facts, plan, and execution progress together.</p>}
    <a href="#agent-problem-solving-model" style={{display:'inline-block',marginTop:9,color:'#c4b5fd',fontSize:12,textDecoration:'none'}}>View the 5-step problem-solving model →</a>
   </article>
   <article style={{border:'1px solid rgba(255,255,255,0.08)',borderRadius:14,padding:'13px 14px',background:'rgba(255,255,255,0.02)'}}><div style={{color:'#a78bfa',fontSize:10,textTransform:'uppercase',letterSpacing:'0.12em'}}>Matter History</div><strong style={{display:'block',marginTop:4,color:'#ede9fe',fontSize:14}}>{previousMatters.length?'Your Agent remembers earlier matters':'Earlier matters will appear here'}</strong><div style={{display:'grid',gap:6,marginTop:9}}>{previousMatters.length?previousMatters.map((item)=><button key={item.id} type="button" onClick={()=>switchMatter(item)} disabled={Boolean(switchingId)} aria-label={`Open matter: ${item.title}`} style={{width:'100%',textAlign:'left',cursor:switchingId?'wait':'pointer',border:'1px solid rgba(255,255,255,0.08)',borderRadius:10,padding:'8px 9px',background:switchingId===item.id?'rgba(124,58,237,0.16)':'rgba(255,255,255,0.015)'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><span style={{color:'#d8d4e3',fontSize:11,fontWeight:600}}>{item.title}</span><span style={{color:'#817b8e',fontSize:9}}>{switchingId===item.id?'Opening…':shortDate(item.updatedAt)}</span></div><div style={{color:'#8f899b',fontSize:9,marginTop:3}}>{STATUS_LABEL[item.status]} · {item.thread.length} messages · {Object.keys(item.knownFacts).length} facts</div></button>):<p style={{color:'#858091',fontSize:11,lineHeight:1.5,margin:0}}>When you start a different matter, this Agent will keep the earlier matter in history instead of treating every conversation as a brand-new relationship.</p>}</div>{previousMatters.length>0&&<p style={{color:'#858091',fontSize:10,lineHeight:1.45,margin:'8px 0 0'}}>Open any earlier matter to restore its conversation, facts, session, and Action Blueprint together.</p>}</article>
  </div>
 </section>
}
