'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { RuntimeBadge, useOrderRuntime } from '../components/OrderRuntimeBridge'

type Stage = 'estimate' | 'accepted' | 'paid' | 'processing' | 'delivered' | 'completed'
type RequestType = 'text' | 'date' | 'amount' | 'choice' | 'image' | 'pdf' | 'file'
type SupplementItem = { id:string; label:string; type:RequestType; required:boolean; answer?:string; attachments?:Array<{name:string;size:number;type:string}>; complete?:boolean }
type DeliveryFile = { id:string; name:string; size:number; type:string; category:string; version:number }
type DemoState = { stage:Stage; amount:number; serviceTitle:string; scope:string; agentMessages:string[]; customerMessages:string[]; supplementItems:SupplementItem[]; supplementStatus?:'draft'|'collecting'|'complete'; deliveryNote?:string; deliveryFiles:DeliveryFile[]; deliverySubmittedAt?:string; updatedAt?:string; settlement?:'ready'|'paid' }

const KEY='goaa_order_demo_v1'
const initial:DemoState={stage:'estimate',amount:600,serviceTitle:'Life Protection Planning Service',scope:'Professional analysis, plan explanation, and follow-up service per the confirmed scope.',agentMessages:[],customerMessages:[],supplementItems:[],supplementStatus:'draft',deliveryFiles:[]}
const steps:Array<[Stage,string]>=[['estimate','Estimate Sent'],['accepted','Customer Accepted'],['paid','Customer Paid'],['processing','Service in Progress'],['delivered','Delivered'],['completed','Customer Confirmed']]

export default function AgentOrderDemoPage(){
 const runtime=useOrderRuntime('agent')
 const[state,setState]=useState<DemoState>(initial);const[message,setMessage]=useState('');const[newLabel,setNewLabel]=useState('');const[newType,setNewType]=useState<RequestType>('text');const[deliveryNote,setDeliveryNote]=useState('')
 useEffect(()=>{if(runtime.data?.mode==='api'){const r=runtime.data.order,pkg=runtime.data.deliveryPackage,sup=runtime.data.supplement;const mappedStage=(r.stage==='waiting_customer'?'processing':r.stage) as Stage;setState(s=>({...s,stage:mappedStage,amount:r.amount,serviceTitle:r.serviceTitle,supplementStatus:sup?.status==='complete'?'complete':sup?'collecting':s.supplementStatus,supplementItems:sup?.items?.map(x=>({id:x.id,label:x.label,type:x.type as RequestType,required:x.required,answer:x.answer,complete:x.status==='answered'||x.status==='complete',attachments:x.files?.map(f=>({name:f.name,size:0,type:'file'}))}))||[],deliveryNote:pkg?.note,deliveryFiles:pkg?.files?.map(f=>({id:f.id,name:f.name,size:f.size||0,type:f.mimeType||'file',category:f.category,version:f.version}))||[],deliverySubmittedAt:pkg?.submittedAt,updatedAt:r.updatedAt,settlement:r.settlement==='paid'?'paid':r.settlement==='ready'?'ready':undefined}));setDeliveryNote(pkg?.note||'');return}hydrate();const onStorage=(e:StorageEvent)=>{if(e.key===KEY)hydrate()};window.addEventListener('storage',onStorage);return()=>window.removeEventListener('storage',onStorage)},[runtime.data])
 function hydrate(){try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);setState({...initial,...parsed,deliveryFiles:parsed.deliveryFiles||[]});setDeliveryNote(parsed.deliveryNote||'')}}catch{}}
 function persist(next:DemoState){const value={...next,updatedAt:new Date().toISOString()};setState(value);localStorage.setItem(KEY,JSON.stringify(value))}
 function patch(values:Partial<DemoState>){persist({...state,...values})}
 function sendMessage(){const clean=message.trim();if(!clean)return;patch({agentMessages:[...state.agentMessages,clean]});setMessage('')}
 function addSupplement(){const clean=newLabel.trim();if(!clean)return;patch({supplementItems:[...state.supplementItems,{id:String(Date.now()),label:clean,type:newType,required:true,complete:false}],supplementStatus:'draft'});setNewLabel('')}
 function removeSupplement(id:string){patch({supplementItems:state.supplementItems.filter(x=>x.id!==id),supplementStatus:'draft'})}
 function startCollection(){if(!state.supplementItems.length)return;patch({supplementStatus:'collecting'})}
 function addDeliveryFiles(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;const next=files.map((f,i)=>({id:`df-${Date.now()}-${i}`,name:f.name,size:f.size,type:f.type||'file',category:guessCategory(f.name),version:1}));patch({deliveryFiles:[...state.deliveryFiles,...next]})}
 function removeDeliveryFile(id:string){patch({deliveryFiles:state.deliveryFiles.filter(x=>x.id!==id)})}
 function updateDeliveryCategory(id:string,category:string){patch({deliveryFiles:state.deliveryFiles.map(x=>x.id===id?{...x,category}:x)})}
 function submitDelivery(){if(!state.deliveryFiles.length)return;patch({stage:'delivered',deliveryNote:deliveryNote.trim(),deliverySubmittedAt:new Date().toISOString()})}
 const stageIndex=steps.findIndex(([id])=>id===state.stage),customerAccepted=stageIndex>=1,paid=stageIndex>=2,processing=stageIndex>=3,delivered=stageIndex>=4,completed=stageIndex>=5
 const settlementLabel=state.settlement==='paid'?'In Stripe Connect Payout':completed?'Settlement Ready':'Locked Until Completion';const customerLatest=useMemo(()=>state.customerMessages.slice(-3).reverse(),[state.customerMessages]);const collected=state.supplementItems.filter(x=>x.complete).length;const allCollected=state.supplementItems.length>0&&collected===state.supplementItems.length
 return <main style={{minHeight:'100vh',background:'#0d0b12',color:'#f7f5fb',fontFamily:'Inter,Arial,sans-serif',padding:'28px 18px 70px'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{color:'#9d7cff',fontSize:12,fontWeight:800}}>GOAA AGENT · ORDER WORKSPACE</div><h1 style={{margin:'7px 0 0',fontSize:30}}>Service Order Workspace</h1></div><div style={{display:'flex',gap:10,alignItems:'center'}}><RuntimeBadge mode={runtime.data?.mode} loading={runtime.loading} error={runtime.error}/><button style={secondary} onClick={()=>{localStorage.removeItem(KEY);setState(initial);setDeliveryNote('')}}>Reset Demo</button></div></div>
  <section style={{...card,marginTop:18,background:'linear-gradient(145deg,#211735,#15121d)'}}><div style={{color:'#a993f3',fontSize:12,fontWeight:800}}>SERVICE ORDER #{runtime.orderId}</div><h2 style={{margin:'9px 0 5px'}}>{state.serviceTitle}</h2><div style={{color:'#9b94a4',fontSize:13}}>California · Professional Service Order</div><p style={{color:'#bbb4c6',lineHeight:1.65,marginBottom:0}}>Supplement tasks automatically track gaps; final deliverables are saved to this order through the delivery package.</p></section>
  <section style={card}><div style={{fontWeight:800}}>Order Tracking</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:8,marginTop:14}}>{steps.map(([id,label],i)=><div key={id} style={{padding:'11px 9px',borderRadius:10,border:'1px solid #302a39',textAlign:'center',fontSize:12,fontWeight:700,background:i<stageIndex?'#193523':i===stageIndex?'#2b2146':'#121018',color:i<stageIndex?'#86efac':i===stageIndex?'#cbb9ff':'#77717f'}}>{label}</div>)}</div></section>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(300px,.65fr)',gap:16,marginTop:16}}><div style={{display:'grid',gap:16}}>
   <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:18,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Service Estimate</h2><p style={{color:'#9993a4',fontSize:13}}>Fulfillment starts after the customer accepts and pays.</p></div><div style={{fontSize:30,fontWeight:850}}>${state.amount}</div></div><label style={labelStyle}>Service Name<input disabled={customerAccepted} value={state.serviceTitle} onChange={e=>patch({serviceTitle:e.target.value})} style={input}/></label><label style={labelStyle}>Estimated Fee (USD)<input disabled={customerAccepted} value={state.amount} onChange={e=>patch({amount:Number(e.target.value.replace(/[^0-9.]/g,''))||0})} style={input}/></label><label style={labelStyle}>Scope<textarea disabled={customerAccepted} value={state.scope} onChange={e=>patch({scope:e.target.value})} style={{...input,minHeight:100,resize:'vertical'}}/></label>{!customerAccepted&&<button style={primary} onClick={()=>patch({stage:'estimate'})}>Send Estimate</button>}{customerAccepted&&!paid&&<Status text="Customer accepted the estimate. Awaiting payment."/>}{paid&&!processing&&<button style={primary} onClick={()=>patch({stage:'processing'})}>Start Service</button>}{delivered&&!completed&&<Status text="Delivery package sent. Awaiting customer confirmation."/>}{completed&&<Status text="Customer confirmed completion. Settlement conditions met." good/>}</section>
   <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Information Collection</h2><p style={{color:'#9993a4',fontSize:13,lineHeight:1.6,marginBottom:0}}>Define the required items once; the system collects them automatically. When complete, review the full package at once.</p></div><span style={{fontSize:12,color:allCollected?'#86efac':'#cbb9ff'}}>{state.supplementItems.length?`${collected}/${state.supplementItems.length} Collected`:'Not Created'}</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 150px auto',gap:8,marginTop:14}}><input value={newLabel} onChange={e=>setNewLabel(e.target.value)} placeholder="e.g., last two years of Tax Return" style={input}/><select value={newType} onChange={e=>setNewType(e.target.value as RequestType)} style={input}><option value="text">Text</option><option value="date">Date</option><option value="amount">Amount</option><option value="choice">Choice</option><option value="image">Image</option><option value="pdf">PDF</option><option value="file">File</option></select><button style={secondary} onClick={addSupplement}>+ Add</button></div><div style={{display:'grid',gap:8,marginTop:12}}>{state.supplementItems.map(item=><div key={item.id} style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',padding:'11px 12px',border:'1px solid #302a39',borderRadius:10,background:'#121018'}}><div><div style={{fontWeight:700,fontSize:13}}>{item.label}</div><div style={{fontSize:11,color:item.complete?'#86efac':'#8f8999',marginTop:4}}>{typeLabel(item.type)} · {item.complete?'Collected':'Awaiting Customer'}</div></div><button style={secondary} onClick={()=>removeSupplement(item.id)}>Delete</button></div>)}</div>{state.supplementItems.length>0&&state.supplementStatus!=='collecting'&&!allCollected&&<button style={{...primary,marginTop:14}} onClick={startCollection}>Start Collection</button>}{state.supplementStatus==='collecting'&&!allCollected&&<Status text="The system is collecting each item and checking for gaps."/>}{allCollected&&<div style={{marginTop:14,padding:14,borderRadius:12,background:'#132219',color:'#a9edbc'}}><b>✓ Full Information Package Ready</b></div>}</section>
   {processing&&<section style={{...card,borderColor:'#4c3b70'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Final Delivery Package</h2><p style={{color:'#9993a4',fontSize:13,lineHeight:1.6,marginBottom:0}}>Deliver tax returns, policies, receipts, immigration documents, approvals, or the final report as one package to the customer.</p></div><span style={{fontSize:12,color:'#cbb9ff'}}>{state.deliveryFiles.length} files</span></div><label style={labelStyle}>Delivery Note<textarea value={deliveryNote} onChange={e=>setDeliveryNote(e.target.value)} placeholder="e.g., This service is complete. Attachments include final files and receipts." style={{...input,minHeight:88,resize:'vertical'}}/></label><label style={{...primary,display:'inline-block',marginTop:14}}>+ Upload Delivery Files<input type="file" multiple onChange={addDeliveryFiles} style={{display:'none'}}/></label><div style={{display:'grid',gap:8,marginTop:12}}>{state.deliveryFiles.map(file=><div key={file.id} style={{padding:12,border:'1px solid #302a39',borderRadius:10,background:'#121018',display:'grid',gridTemplateColumns:'1fr 160px auto',gap:9,alignItems:'center'}}><div><b style={{fontSize:13}}>📄 {file.name}</b><div style={{fontSize:11,color:'#8f8999',marginTop:4}}>Version {file.version} · {formatSize(file.size)}</div></div><select value={file.category} onChange={e=>updateDeliveryCategory(file.id,e.target.value)} style={{...input,marginTop:0}}><option>Final Files</option><option>Government/Receipt</option><option>Policy/Contract</option><option>Tax Documents</option><option>Approval/Notice</option><option>Service Report</option><option>Other</option></select><button onClick={()=>removeDeliveryFile(file.id)} style={secondary}>Delete</button></div>)}</div><button disabled={!state.deliveryFiles.length} onClick={submitDelivery} style={{...primary,marginTop:14,opacity:state.deliveryFiles.length?1:.45}}>Submit Delivery Package to Customer</button></section>}
  </div><aside style={{display:'grid',gap:16,alignContent:'start'}}><section style={card}><h2 style={{margin:0,fontSize:18}}>Payment & Settlement</h2><div style={{display:'grid',gap:10,marginTop:14}}><Mini label="Customer Confirmation" value={customerAccepted?'Accepted':'Awaiting Acceptance'}/><Mini label="Stripe Payment" value={paid?`$${state.amount} Paid`:'Not Paid'}/><Mini label="Agent Settlement" value={settlementLabel}/></div>{completed&&state.settlement!=='paid'&&<button style={{...primary,marginTop:14}} onClick={()=>patch({settlement:'paid'})}>Simulate Stripe Connect Settlement</button>}</section><section style={card}><h2 style={{margin:0,fontSize:18}}>Chat with Customer</h2><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="e.g., estimated completion time…" style={{...input,minHeight:78}}/><button style={{...primary,marginTop:9}} onClick={sendMessage}>Send to Customer</button>{customerLatest.length>0&&<div style={{marginTop:12}}><div style={{color:'#8f8999',fontSize:12}}>Recent Customer Replies</div>{customerLatest.map((m,i)=><div key={i} style={{marginTop:7,padding:9,borderRadius:9,background:'#121018',fontSize:12}}>{m}</div>)}</div>}</section></aside></div>
 </div></main>
}
function guessCategory(name:string){const n=name.toLowerCase();if(n.includes('tax')||n.includes('1040')||n.includes('w-2'))return'Tax Documents';if(n.includes('policy')||n.includes('insurance'))return'Policy/Contract';if(n.includes('receipt')||n.includes('i-797')||n.includes('uscis'))return'Government/Receipt';return'Final Files'}
function formatSize(v:number){if(v<1024)return `${v} B`;if(v<1024*1024)return `${Math.round(v/1024)} KB`;return `${(v/1024/1024).toFixed(1)} MB`}
function typeLabel(v:RequestType){return ({text:'Text',date:'Date',amount:'Amount',choice:'Choice',image:'Image',pdf:'PDF',file:'File'} as Record<RequestType,string>)[v]}
function Mini({label,value}:{label:string;value:string}){return <div style={{display:'flex',justifyContent:'space-between',gap:12,paddingBottom:9,borderBottom:'1px solid #292530',fontSize:13}}><span style={{color:'#8f8999'}}>{label}</span><span>{value}</span></div>}
function Status({text,good=false}:{text:string;good?:boolean}){return <div style={{marginTop:12,padding:12,borderRadius:10,background:good?'#193523':'#171321',color:good?'#86efac':'#cdbff7',fontSize:13}}>{text}</div>}
const card={background:'#17151e',border:'1px solid #2b2734',borderRadius:18,padding:20} as const
const primary={border:0,borderRadius:10,background:'#7655df',color:'#fff',padding:'10px 14px',fontWeight:750,cursor:'pointer'} as const
const secondary={border:'1px solid #3b3545',borderRadius:10,background:'transparent',color:'#c7c0cf',padding:'9px 13px',cursor:'pointer'} as const
const input={width:'100%',boxSizing:'border-box' as const,border:'1px solid #393342',borderRadius:10,background:'#100e15',color:'#f7f5fb',padding:'11px 12px',outline:'none',marginTop:7} as const
const labelStyle={display:'block',color:'#aaa3b5',fontSize:12,fontWeight:700,marginTop:12} as const
